// Generated by gencpp from file rgb2cloud/pcArea.msg
// DO NOT EDIT!


#ifndef RGB2CLOUD_MESSAGE_PCAREA_H
#define RGB2CLOUD_MESSAGE_PCAREA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point32.h>

namespace rgb2cloud
{
template <class ContainerAllocator>
struct pcArea_
{
  typedef pcArea_<ContainerAllocator> Type;

  pcArea_()
    : listPcPoint()  {
    }
  pcArea_(const ContainerAllocator& _alloc)
    : listPcPoint(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point32_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point32_<ContainerAllocator> >> _listPcPoint_type;
  _listPcPoint_type listPcPoint;





  typedef boost::shared_ptr< ::rgb2cloud::pcArea_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rgb2cloud::pcArea_<ContainerAllocator> const> ConstPtr;

}; // struct pcArea_

typedef ::rgb2cloud::pcArea_<std::allocator<void> > pcArea;

typedef boost::shared_ptr< ::rgb2cloud::pcArea > pcAreaPtr;
typedef boost::shared_ptr< ::rgb2cloud::pcArea const> pcAreaConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rgb2cloud::pcArea_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rgb2cloud::pcArea_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rgb2cloud::pcArea_<ContainerAllocator1> & lhs, const ::rgb2cloud::pcArea_<ContainerAllocator2> & rhs)
{
  return lhs.listPcPoint == rhs.listPcPoint;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rgb2cloud::pcArea_<ContainerAllocator1> & lhs, const ::rgb2cloud::pcArea_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rgb2cloud

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rgb2cloud::pcArea_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rgb2cloud::pcArea_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgb2cloud::pcArea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rgb2cloud::pcArea_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgb2cloud::pcArea_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rgb2cloud::pcArea_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rgb2cloud::pcArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1910f595f1099a0b020344db77cf9645";
  }

  static const char* value(const ::rgb2cloud::pcArea_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1910f595f1099a0bULL;
  static const uint64_t static_value2 = 0x020344db77cf9645ULL;
};

template<class ContainerAllocator>
struct DataType< ::rgb2cloud::pcArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rgb2cloud/pcArea";
  }

  static const char* value(const ::rgb2cloud::pcArea_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rgb2cloud::pcArea_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point32[] listPcPoint\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point32\n"
"# This contains the position of a point in free space(with 32 bits of precision).\n"
"# It is recommeded to use Point wherever possible instead of Point32.  \n"
"# \n"
"# This recommendation is to promote interoperability.  \n"
"#\n"
"# This message is designed to take up less space when sending\n"
"# lots of points at once, as in the case of a PointCloud.  \n"
"\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
;
  }

  static const char* value(const ::rgb2cloud::pcArea_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rgb2cloud::pcArea_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.listPcPoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pcArea_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rgb2cloud::pcArea_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rgb2cloud::pcArea_<ContainerAllocator>& v)
  {
    s << indent << "listPcPoint[]" << std::endl;
    for (size_t i = 0; i < v.listPcPoint.size(); ++i)
    {
      s << indent << "  listPcPoint[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point32_<ContainerAllocator> >::stream(s, indent + "    ", v.listPcPoint[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RGB2CLOUD_MESSAGE_PCAREA_H
