// Generated by gencpp from file rgb2cloud/rgb2cloud.msg
// DO NOT EDIT!


#ifndef RGB2CLOUD_MESSAGE_RGB2CLOUD_H
#define RGB2CLOUD_MESSAGE_RGB2CLOUD_H

#include <ros/service_traits.h>


#include <rgb2cloud/rgb2cloudRequest.h>
#include <rgb2cloud/rgb2cloudResponse.h>


namespace rgb2cloud
{

struct rgb2cloud
{

typedef rgb2cloudRequest Request;
typedef rgb2cloudResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rgb2cloud
} // namespace rgb2cloud


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rgb2cloud::rgb2cloud > {
  static const char* value()
  {
    return "cbe6659d39342a7a2160bf2d36c45404";
  }

  static const char* value(const ::rgb2cloud::rgb2cloud&) { return value(); }
};

template<>
struct DataType< ::rgb2cloud::rgb2cloud > {
  static const char* value()
  {
    return "rgb2cloud/rgb2cloud";
  }

  static const char* value(const ::rgb2cloud::rgb2cloud&) { return value(); }
};


// service_traits::MD5Sum< ::rgb2cloud::rgb2cloudRequest> should match
// service_traits::MD5Sum< ::rgb2cloud::rgb2cloud >
template<>
struct MD5Sum< ::rgb2cloud::rgb2cloudRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rgb2cloud::rgb2cloud >::value();
  }
  static const char* value(const ::rgb2cloud::rgb2cloudRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgb2cloud::rgb2cloudRequest> should match
// service_traits::DataType< ::rgb2cloud::rgb2cloud >
template<>
struct DataType< ::rgb2cloud::rgb2cloudRequest>
{
  static const char* value()
  {
    return DataType< ::rgb2cloud::rgb2cloud >::value();
  }
  static const char* value(const ::rgb2cloud::rgb2cloudRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rgb2cloud::rgb2cloudResponse> should match
// service_traits::MD5Sum< ::rgb2cloud::rgb2cloud >
template<>
struct MD5Sum< ::rgb2cloud::rgb2cloudResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rgb2cloud::rgb2cloud >::value();
  }
  static const char* value(const ::rgb2cloud::rgb2cloudResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rgb2cloud::rgb2cloudResponse> should match
// service_traits::DataType< ::rgb2cloud::rgb2cloud >
template<>
struct DataType< ::rgb2cloud::rgb2cloudResponse>
{
  static const char* value()
  {
    return DataType< ::rgb2cloud::rgb2cloud >::value();
  }
  static const char* value(const ::rgb2cloud::rgb2cloudResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RGB2CLOUD_MESSAGE_RGB2CLOUD_H
